Update compileUm.yml

diff --git a/.github/workflows/compileUm.yml b/.github/workflows/compileUm.yml
--- a/.github/workflows/compileUm.yml
+++ b/.github/workflows/compileUm.yml
@@ -109,45 +109,53 @@ jobs:
     - name: Verify Visual Studio Build Tools
       shell: powershell
       run: |
-
+    
         Write-Host "========== Locate Visual Studio =========="
-
+    
         $vswhere = `
           "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
-
-
+    
+    
         if (!(Test-Path $vswhere)) {
-
-          Write-Error "vswhere.exe not found"
-          exit 1
-
+    
+            Write-Error "vswhere.exe not found"
+            exit 1
+    
         }
-
-
+    
+    
         $msbuild = & $vswhere `
           -latest `
           -products * `
           -requires Microsoft.Component.MSBuild `
           -find MSBuild\**\Bin\MSBuild.exe
-
-
+    
+    
         Write-Host ""
-        Write-Host "MSBuild candidates:"
-        $msbuild
-
-
-        if (!$msbuild) {
-
-          Write-Error "MSBuild not found"
-          exit 1
-
+        Write-Host "MSBuild path:"
+        Write-Host $msbuild
+    
+    
+        if ([string]::IsNullOrWhiteSpace($msbuild)) {
+    
+            Write-Error "MSBuild not found"
+            exit 1
+    
         }
-
-
+    
+    
+        if (!(Test-Path $msbuild)) {
+    
+            Write-Error "MSBuild path invalid"
+            exit 1
+    
+        }
+    
+    
         Write-Host ""
-        Write-Host "Testing MSBuild..."
-
-        & $msbuild[0] -version
+        Write-Host "========== MSBuild Version =========="
+    
+        & "$msbuild" -version
 
 
 
@@ -157,31 +165,23 @@ jobs:
     - name: Build Driver x64 ReleaseSigned
       shell: powershell
       run: |
-
+    
         $vswhere = `
           "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
-
-
+    
+    
         $msbuild = & $vswhere `
           -latest `
           -products * `
           -requires Microsoft.Component.MSBuild `
           -find MSBuild\**\Bin\MSBuild.exe
-
-
-        if (!$msbuild) {
-
-          Write-Error "MSBuild missing"
-          exit 1
-
-        }
-
-
+    
+    
         Write-Host "Using MSBuild:"
-        Write-Host $msbuild[0]
-
-
-        & $msbuild[0] `
+        Write-Host $msbuild
+    
+    
+        & "$msbuild" `
           src\AmtPtpDeviceUsbUm\MagicTrackpad2PtpDevice.vcxproj `
           /m `
           /v:detailed `
